# Imports

In [35]:
using LimberJack

In [36]:
#include("/home/jaime/PhD/LimberJack.jl/src/LimberJack.jl")

In [37]:
cosmo = Cosmology(0.30, 0.05, 0.67, 0.96, 0.81, nk=2, nz=2, tk_mode="EisHu")
k = [0.001, 0.01, 0.1, 1.0, 10.0]

[5.177538156159547e11 99767.40935717999; 5.268121089636441e10 10151.287686169508]Any[5.177538156159547e11, 99767.40935717999, 5.268121089636441e10, 10151.287686169508]

5-element Vector{Float64}:
  0.001
  0.01
  0.1
  1.0
 10.0

In [62]:
u = Array{Float64}([])

Float64[]

In [65]:
append!(u, transpose([2., 2.]))

6-element Vector{Float64}:
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0

In [50]:
v = Array([5.177538156159547e11, 99767.40935717999, 5.268121089636441e10, 10151.287686169508])

4-element Vector{Float64}:
     5.177538156159547e11
 99767.40935717999
     5.268121089636441e10
 10151.287686169508

In [46]:
[5.177538156159547e11 99767.40935717999; 5.268121089636441e10 10151.287686169508]

2×2 Matrix{Float64}:
 5.17754e11  99767.4
 5.26812e10  10151.3

In [49]:
transpose(reshape(v, 2, 2))

LoadError: TypeError: in Type{...} expression, expected UnionAll, got a value of type Matrix{Any}

In [38]:
PkL = cosmo.lin_Pk(0, k)

5-element Vector{Float64}:
 5.1774915582785223e11
 5.17702557946828e11
 5.172365791365855e11
 5.125767910341605e11
 4.6597891000991034e11

In [20]:
Pk = cosmo.Pk(0, k)

5-element Vector{Float64}:
 5.1774915582785223e11
 5.17702557946828e11
 5.172365791365855e11
 5.125767910341605e11
 4.6597891000991034e11

In [21]:
print(cosmology.Pk(0,k))

LoadError: UndefVarError: cosmology not defined

In [22]:
print(cosmology.lin_Pk(0,k))

LoadError: UndefVarError: cosmology not defined

In [23]:
plot(cosmology.ks, Pk, yaxis=:log, xaxis=:log, label = "Non-linear")
plot!(cosmology.ks, PkL, yaxis=:log, xaxis=:log, label = "Linear")
xlabel!("k")
ylabel!("Pk")

LoadError: UndefVarError: plot not defined

In [24]:
wz = @. exp(-0.5*((cosmology.zs-0.5)/0.05)^2)
numbercounts = LimberJack.NumberCountsTracer(cosmology, cosmology.zs, wz, 2.);
weaklensing = LimberJack.WeakLensingTracer(cosmology, cosmology.zs, wz);
cmblensing = LimberJack.CMBLensingTracer(cosmology);

LoadError: UndefVarError: cosmology not defined

In [25]:
ls = [10, 30, 100, 300];

In [26]:
[LimberJack.angularCℓ(cosmology, numbercounts,
                     numbercounts, l) for l in ls]

LoadError: UndefVarError: cosmology not defined

In [27]:
[LimberJack.angularCℓ(cosmology, numbercounts,
                     weaklensing, l) for l in ls]

LoadError: UndefVarError: cosmology not defined

In [28]:
[LimberJack.angularCℓ(cosmology, weaklensing,
                     weaklensing, l) for l in ls]

LoadError: UndefVarError: cosmology not defined

In [29]:
[LimberJack.angularCℓ(cosmology, numbercounts,
                     cmblensing, l) for l in ls]

LoadError: UndefVarError: cosmology not defined

In [30]:
[LimberJack.angularCℓ(cosmology, weaklensing,
                     cmblensing, l) for l in ls]

LoadError: UndefVarError: cosmology not defined